version: '3'

services:
    server:
        image: nginx:alpine
        container_name: lig_server
        ports:
          - "80:80"
        volumes:
            - './app:/var/www/app'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf      
    php:
        build: ./docker/php
        container_name: lig_php        
        volumes:
            - './app:/var/www/app'         
    db:
        image: mysql:5.7                 
        container_name: lig_mysql
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: sifre      
